### ISSUE TITLE
report error of cupy

### ISSUE THREAD

**Issue by machanic** [escorciav/roi_pooling#1] opened 2018-09-11 02:24 UTC
ERROR: test_backward_gpu (__main__.TestROIPooling2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 241, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_roi_pooling.py", line 80, in test_backward_gpu
    self.check_backward(x_var, rois_var)
  File "test/test_roi_pooling.py", line 69, in check_backward
    raise_exception=True))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 190, in gradcheck
    output = _differentiable_outputs(func(*inputs))
  File "/home1/machen/roi_pooling/roi_pooling/functions/roi_pooling.py", line 257, in roi_pooling_2d
    return ROIPooling2d.apply(input, rois, output_size, spatial_scale)
  File "/home1/machen/roi_pooling/roi_pooling/functions/roi_pooling.py", line 201, in forward
    pooled_height=self.output_h, pooled_width=self.output_w)
  File "cupy/util.pyx", line 48, in cupy.util.memoize.decorator.ret
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyinn/utils.py", line 20, in load_kernel
    kernel_code = cupy.cuda.compile_with_cache(code)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /tmp/tmp_vrmafnj/kern.cu(7): error: identifier "None" is undefined

1 error detected in the compilation of "/tmp/tmp_vrmafnj/kern.cu".

======================================================================
ERROR: test_forward_gpu (__main__.TestROIPooling2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 241, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

**Comment by machanic** [comment] 2018-10-05 06:49
Traceback (most recent call last):                                              
  File "face_classification/train_fcn.py", line 171, in <module>
    main()
  File "face_classification/train_fcn.py", line 167, in main
    trainer.train()
  File "/home1/machen/cnn_interpret/face_classification/torchfcn/trainer.py", line 127, in train
    self.train_epoch()
  File "/home1/machen/cnn_interpret/face_classification/torchfcn/trainer.py", line 109, in train_epoch
    loss.backward()
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/autograd/function.py", line 188, in wrapper
    outputs = fn(ctx, *args)
  File "/home1/machen/cnn_interpret/face_classification/roi_pooling/functions/roi_pooling.py", line 234, in backward
    pooled_width=self.output_w)
  File "cupy/util.pyx", line 48, in cupy.util.memoize.decorator.ret
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/pyinn-0.0.1-py3.5.egg/pyinn/utils.py", line 20, in load_kernel
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 166, in compile_with_cache
    ls.add_ptr_data(ptx, six.u('cupy.ptx'))
  File "cupy/cuda/function.pyx", line 206, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/function.pyx", line 208, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/driver.pyx", line 119, in cupy.cuda.driver.linkAddData
  File "cupy/cuda/driver.pyx", line 75, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_UNKNOWN: unknown error

**Comment by escorciav** [comment] 2018-10-05 06:56
Sorry, that you are facing issues. I don't understand this, thus I'm closing the issue.

- I don't provide any `face_classification/train_fcn.py` file.

- I posted bits of advice for installation in #2

**Closed as completed by escorciav** 2018-10-05 06:56 UTC

**Comment by escorciav** [comment] 2019-04-06 00:28
I found some parts of the traceback error recently.
1. The cause is reported in #4 
1. I outline a quick-fix in #5
